version: '3.4'

services:
    app:
        container_name: app
        build: 
            context: app
            dockerfile: Dockerfile
        ports:
          - "3000:3000"
    mongodb:
        restart: unless-stopped
        container_name: mongodb
        build: 
            context: mongodb
            dockerfile: Dockerfile
        ports:
          - 27017:27017
        volumes:
          - ./mongodb/db:/data/db